name: dtlAnimations
main: net.dandielo.bukkit.DtlAnimations
version: 1.3.2
depend: [WorldEdit]
softdepend: [Denizen]
description: >
             | Animations using schematics as frames
commands:
  anim: 
    description: dtlAnimation commands
  frame:  
    description: animation frame commands
